# Generated by Django 5.0.9 on 2024-11-23 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Subject",
            new_name="subject",
        ),
    ]
